name: pipeline

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: pipeline_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: pipeline_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ollama:
    build: .
    container_name: pipeline_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: pipeline_streamlit
    depends_on:
      - kafka
      - ollama
    ports:
      - "8501:8501"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      OLLAMA_BASE_URL: http://ollama:11434
      APP_IN_CONTAINER: "true"
    volumes:
      - ./historical_data_lake:/app/historical_data_lake
      - ./spark_checkpoints:/app/spark_checkpoints
    restart: unless-stopped

volumes:
  ollama_data:
  kafka_data:
